export const CLASSES = Object.freeze({
  WARRIOR: "warrior",
  PALADIN: "paladin",
  HUNTER: "hunter",
  ROGUE: "rogue",
  PRIEST: "priest",
  SHAMAN: "shaman",
  MAGE: "mage",
  WARLOCK: "warlock",
  MONK: "monk",
  DRUID: "druid",
  DEMONHUNTER: "demonhunter",
  DEATHKNIGHT: "deathknight",
  EVOKER: "evoker",
  GENERAL: "general",
})
